export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home/Home";
export { default as Gallery } from "./Gallery/Gallery";
export { default as Events } from "./Events/Events";
export { default as Resources } from "./Resources/Resources";
export { default as About } from "./AboutUs/About";
export { default as OurTeam } from "./OurTeam/OurTeam";
export { default as Contact } from "./Contact/Contact";
