export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home/Home";
export { default as About } from "./AboutUs/About";
// export { default as Contact } from "./Contact";
export { default as CarouselContainer } from "./Home/CarouselContainer";
export { default as Intro } from "./Home/Intro";
// export { default as Announcement } from "./Announcement";
export { default as OverlayText } from "./Home/OverlayText";
export { default as OurTeam } from "./OurTeam/OurTeam";
export { default as Contact } from "./Contact/Contact.jsx";
